"""
sample_main.py -- Sample stub showing the expected CLI contract for the
Project 2 inference script. This is NOT a working schema-linking model;
it produces an empty schema_links dict for every question so you can sanity-
check the I/O wiring of your evaluation pipeline.

Your real main.py must accept the same CLI flags and produce the same output
shape, but generated by your fine-tuned SLM.

CLI contract:
    python main.py --input  <questions_input.json> \
                   --output <predictions.json> \
                   [--schemas_dir <path>]

Input shape (list of dicts):
    [
      {"question_id": 1, "db_id": "<DB_NAME>", "question": "<NL question>"},
      ...
    ]

Output shape (list of dicts):
    [
      {"question_id": 1,
       "schema_links": {"TableName1": ["Col1","Col2"], "TableName2": ["ColX"]}},
      ...
    ]

The output identifiers should use the SAME casing as in the schema files
(case-insensitive grading is applied, but matching casing makes debugging easier).
"""
import argparse
import json


def predict_schema_links(question, db_id, schemas_dir):
    """Replace this with your model's inference logic."""
    return {}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--input',  required=True)
    ap.add_argument('--output', required=True)
    ap.add_argument('--schemas_dir', default='./schemas')
    args = ap.parse_args()

    with open(args.input) as f:
        items = json.load(f)
    preds = []
    for it in items:
        links = predict_schema_links(it['question'], it['db_id'], args.schemas_dir)
        preds.append({'question_id': it['question_id'], 'schema_links': links})
    with open(args.output, 'w') as f:
        json.dump(preds, f, indent=2)
    print(f"Wrote {len(preds)} predictions to {args.output}")


if __name__ == '__main__':
    main()
